name: 'Dreadjim '
favicon: null
layout_spectrum: 0.7351566227152944
typography_spectrum: 0.5334173443261534
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.3292204630561173
  lightness: 0.7733510597608984
  saturation: 0.44227603799663484
  rhythmicContrast: 0.9250012398697436
purpose: []
